major improvment in MKV-conversion helpers; should make them their own project

diff --git a/bin/ch2mkv b/bin/ch2mkv
--- a/bin/ch2mkv
+++ b/bin/ch2mkv
@@ -2,7 +2,7 @@
 
 SELF="$0"
 SELFNAME="$(basename "$SELF")"
-ARGS="$@"
+
 
 #############################
 ### Customizable Settings ###
@@ -101,10 +101,18 @@ fi
 # lets give at least a *chance* to interrupt before the we do
 # destructive things like overitting the original files O.O
 countdown_delay() {
-    sleep 1 ; pwarn " (3)"
-    sleep 1 ; pwarn " (2)"
-    sleep 1 ; pwarn " (1)"
-    sleep 1 ; pwarn " (0)"
+    local -i x=4
+    pwarn " // DELAY\t(${x}s) //"
+    while (( x>0 )) ; do
+        if $color ; then
+            pwarn " //  \e[0;35m-* \e[1;36m$x\e[0;35m *-\e[1;34m\t     //"
+        else
+            pwarn " //  -* $x *-\t     //"
+        fi
+        sleep 1
+        (( x=x-1 ))
+    done
+    pwarn " //  -* 0 *-\tGO!! //"
 }
 
 safe_make_tempfile() {
@@ -188,6 +196,7 @@ run_the_conversion() {
 
     echo mkclean --doctype 2 --remux --optimize "$tmp1" "$tmp2"
     mkclean --doctype 2 --remux --optimize "$tmp1" "$tmp2" || died_in "mkclean"
+    touch -r "$orig" "$tmp2"
 
     diffver "$orig" "$tmp2"
     prln "validating the results..."
@@ -233,84 +242,153 @@ create_defered-finish_script() {
     cat <<EOF > ${defer_sh}
 #!/bin/bash
 
+JOBFILE="${jobfile}"
+SELF="${defer_sh}"
+ORIG_NAME="${orig_basename}"
+ORIGINAL="${orig}"
+STAGING="${dst}"
+TARGET="${dst_real}"
+
 delete_self() {
     echo ">>>"
     echo ">>> Removing our entry in the pending queue:"
-    $(echo_exec "rm" "-f" "${jobfile}")
+    $(echo_exec "rm" "-f" "\${JOBFILE}")
 
     echo ">>>"
     echo ">>> Removing ourself so no trash is left laying around:"
-    $(echo_exec "rm" "-f" "${defer_sh}")
+    $(echo_exec "rm" "-f" "\${SELF}")
 
     echo ">>>"
     echo ">>> Finished succssefully!"
     exit 0
 }
 
-case \$1 in
-    --gettext-commit)
-            echo "Keep the new MKV, replacing the existing ``${orig_basename}>''"
-            exit 0  ;;
-
-    --gettext-rollback)
-            echo "Undo all changes; keep origianl"
-            exit 0  ;;
-
-    --gettext-cancel)
-            echo "Nevermind, just exit, don't touch anything!"
-            exit 0  ;;
-
-    --gettext-question)
-            echo -e "$qtxt"
-            exit 0
-            ;;
-
-    -s | --setup)
-            if [[ -z "${MPLAYER}" ]] ; then
-                if command hash mplayer2 ; then
-                    MPLAYER="mplayer2"
-                elif command hash mplayer ; then
+setup() {
+    if [[ -z "\${MPLAYER}" ]] ; then
+        if command hash mplayer2 ; then
+            MPLAYER="mplayer2"
+        elif command hash mplayer ; then
                     MPLAYER="mplayer"
-                else
-                    echo "!!! ERROR - mplayer not found!"
-                    exit 1
-                fi
-            fi
-
-            if zenity --question --no-wrap --text="${vtxt}" --ok-label="Run MPlayer!" ; then
-                echo ">>> Handing off to mplayer..."
-                mplayer "${dst}"
-                echo ">>> ...back form mplayer!"
-                exit 0
-            else
-                echo "!!! No verification was done!"
-                exit 1
-            fi
-            ;;
-
-    -r | --rollback)
-            echo ">>> Rolling back our changes, and leaving"
-            echo ">>>     ${orig}"
-            echo ">>> alone as the untouched original."
-            $(echo_exec "rm" "-f" "${dst}")
-            delete_self
-            ;;
-
-    -c | --commit)
-            echo ">>> MKV should be verified and checked."
-            echo ">>>"
-            echo ">>> Overiting the original file!!!"
-            $(echo_exec "rm" "${orig}")
-            $(echo_exec "mv" "${dst}" "${dst_real}")
-            delete_self
-            ;;
-
-    *)
-            echo "usage: $0 [--rollback|--commit]"
+        else
+            echo "!!! ERROR - mplayer not found!"
             exit 1
-            ;;
-esac
+        fi
+    fi
 
+    if zenity --question --no-wrap --text="${vtxt}" --ok-label="Run MPlayer!" ; then
+        echo ">>> Handing off to mplayer..."
+        mplayer "\${STAGING}"
+        echo ">>> ...back form mplayer!"
+        exit 0
+    else
+        echo "!!! No verification was done!"
+        exit 1
+    fi
+}
+
+rollback() {
+    echo ">>> Rolling back our changes, and leaving"
+    echo ">>>     \${ORIGINAL}"
+    echo ">>> alone as the untouched original."
+    $(echo_exec "rm" "-f" "\${STAGING}")
+    delete_self
+}
+
+commit() {
+    echo ">>> MKV should be verified and checked."
+    echo ">>>"
+    echo ">>> Overiting the original file!!!"
+    $(echo_exec "rm" "\${ORIGINAL}")
+    $(echo_exec "mv" "\${STAGING}" "\${TARGET}")
+    delete_self
+}
+
+print_ans_commit() {
+    echo -e "Keep the new MKV, OVERWRITES the original"
+}
+
+print_ans_rollback() {
+    echo -e "Undo all changes; keep origianl"
+}
+
+print_ans_cancel() {
+    echo -e "Nevermind, just exit, no changes"
+}
+
+print_question() {
+    echo -e "$qtxt"
+}
+
+filter_pango() {
+    sed -re 's/<[^<>]+>//g'
+}
+
+usage_commands() {
+    echo "COMMANDS:"
+    cat "\$0" | sed -nre "\
+/USEROPT\Wstart/,/USEROPT\Wend/ {
+s/^\s*//
+s/\).*;;//
+s/^# USEROPT.*$//
+s/^-/        -/
+s/# /    /
+p
+}"
+}
+
+usage_job_specific() {
+    echo "This job asks, the flowing about the"
+    echo "initail --setup command:"
+    echo
+    print_question | filter_pango | fold -s -w 50 |  sed -re 's/^/    > /'
+}
+
+usage() {
+    echo "Usage: \$0 <command>"
+    echo
+    echo "This is a job-specific helper tool, to continue a job"
+    echo "that was suspended previously, and was created by:"
+    echo "    $0"
+    echo
+    echo "In most cases, you should run this with the --setup"
+    echo "command first and follow any instructions found there."
+    echo "Afterwords, one of the two commands --rollback "
+    echo "or --commit used be used to finalize everything."
+    echo
+    usage_job_specific
+    echo
+    usage_commands
+}
+
+
+parse_cmd() {
+case \$1 in
+    --gettext-commit)   print_ans_commit   ; exit 0 ;;
+    --gettext-rollback) print_ans_rollback ; exit 0 ;;
+    --gettext-cancel)   print_ans_cancel   ; exit 0 ;;
+    --gettext-question) print_question     ; exit 0 ;;
+
+# USEROPT+start
+# Launches the tasks internal setup tool.
+# Run this setu for this task; should ALWAYS
+# be run before --rollback or --commit are used!
+    -s | --setup) setup ;;
+
+# Finalize the task - either delete the new or
+# the old version, and then delete ourself to cleanup
+    -r | --rollback) rollback ;;
+    -c | --commit)   commit   ;;
+
+# Show this help message
+    -h | --help) usage ; exit 0 ;;
+# USEROPT+end
+    *)           usage ; exit 1 ;;
+esac
+}
+parse_cmd "\$@"
+
+# should never get here!!
+exit 1
 
 EOF
 
@@ -323,16 +401,19 @@ enqueue_deferment_globally() {
 
     prln "add to the must-be-verified queue..."
     cat <<EOF > ${jobfile}
-CATEGORY="ch2mkv-verify"
-SUMMARY="Needs manual check: ${dst}"
-JOB_NAME="ch2mkv/verify/${orig_basename}"
-JOB_EXEC="pendingjob_exec ${defer_sh}"
-CREATOR="${0}"
-ORIG_PWD="${PWD}"
-ORIG_USER_CMD="${SELFNAME} ${orig}"
-COMMIT_CMD="${defer_sh} --commit"
-ROLLBACK_CMD="${defer_sh} --rollback"
-TODO_DESC="Verify that\n    ${dst}\nwas properly generated from:\n    ${orig}\nNote things like A/V skew, missing tracks, etc"
+JOB_ID="${SELFNAME}/verify/${orig_basename}"
+JOB_BIN="${defer_sh}"
+JOB_REQ_FILES="${defer_sh} ${dst} ${orig}"
+JOB_CMD_SETUP="${defer_sh} --setup"
+JOB_CMD_COMMIT="${defer_sh} --commit"
+JOB_CMD_ROLLBACK="${defer_sh} --rollback"
+JOB_ORIG_CREATOR="${SELFNAME}"
+JOB_ORIG_PWD="${PWD}"
+JOB_ORIG_USER_CMD="${SELFNAME} ${orig}"
+JOB_DESC_NAME="${orig_basename}"
+JOB_DESC_CATEGORY="${SELFNAME}-verify"
+JOB_DESC_SHORT="Needs manual check: ${dst}"
+JOB_DESC_FULL="Verify that\n    ${dst}\nwas properly generated from:\n    ${orig}\nNote things like A/V skew, missing tracks, etc"
 EOF
 
     prln "successful logged this task at:"
@@ -378,6 +459,12 @@ convert_to_mkv() {
 
 run_multiple_jobs() {
     local final_retval=0
+    prln "Multiple conversions requested:"
+    for i in "$@"; do
+        prln "  -> $i"
+    done
+    countdown_delay 2
+
     for arg in "$@" ; do
         "$SELF" "$arg"
         ret=$?
@@ -404,6 +491,8 @@ dwim_find_things_to_convert() {
     pwarn "Kill it now if this is incorred!"
     countdown_delay
     prln "Searching with: find . -type f -name '*.avi' -o -name '*.mp4')"
+    list="$(find . -type f -name '*.avi' -o -name '*.mp4')"
+    run_multiple_jobs "$list"
 }
 
 #########################################
@@ -416,7 +505,7 @@ jobcount=$#
 if   (( jobcount<1 )) ; then
     dwim_find_things_to_convert
 elif (( jobcount>1 )) ; then
-    run_multiple_jobs "$ARGS"
+    run_multiple_jobs "$@"
 else
     if [[ "$1" =~ ^/.* ]] ; then
         convert_to_mkv "$1"
diff --git a/bin/joblist b/bin/joblist
--- a/bin/joblist
+++ b/bin/joblist
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-JOBLIST="${HOME}/var/pending_jobs/"
+JOBLIST="${HOME}/var/pending_jobs"
+BADJOBS="${JOBLIST}/_bad"
 
 VERS='1.0'
 HELP="
@@ -9,6 +10,12 @@ usage: $0 [options] [<job-script>]
 
 JOB=""
 INTERACT=false
+
+YAD="$(which yad)"
+ZENITY="$(which zenity)"
+
+yad_p()    {  [[ -n "$YAD"    ]] ; }
+zenity_p() {  [[ -n "$ZENITY" ]] ; }
 
 die() {
     echo -e "$(basename "$0"): ERROR: $@" 1>&2
@@ -23,6 +30,8 @@ while (( $# > 0 )) ; do
         -P | --with-joblist-prefix) JOBLIST="$2"    ; shift 2 ;;
         -x | --exec)                JOB="$2"        ; shift 2 ;;
         -i | --interactive)         INTERACT=true   ; shift   ;;
+             --zenity)              YAD=""          ; shift   ;;
+             --yad)                 ZENITY=""       ; shift   ;;
         --) shift ; break ;;
         -*) echo "bad opt: $1" ; exit 1 ;;
         *)  break ;;
@@ -62,14 +71,45 @@ txt() {
     echo -e "$X"
 }
 
-ask_how_to_proceed() {
-    zenity --list                       \
-        --hide-header                   \
-        --text   "$(txt "$1" question)" \
-        --column "" --column "Option"   \
-        COMMIT   "$(txt "$1" commit)"   \
-        ROLLBACK "$(txt "$1" rollback)" \
+ask_how_to_proceed_yad() {
+    ${YAD}                                                              \
+        --image=gtk-dialog-warning                                      \
+        --window-icon=gtk-dialog-warning                                \
+        --title="how to proceed?"                                       \
+        --text "$(txt "$1" question)"                                   \
+        --center                                                        \
+        --on-top                                                        \
+        --selectable-labels                                             \
+        --button=gtk-apply:1                                            \
+        --button=gtk-undo:2                                             \
+        --button=gtk-cancel:0
+}
+
+ask_how_to_proceed_zenity() {
+    ${ZENITY} --list                                                    \
+        --hide-header                                                   \
+        --text   "$(txt "$1" question)"                                 \
+        --column "" --column "Option"                                   \
+        COMMIT   "$(txt "$1" commit)"                                   \
+        ROLLBACK "$(txt "$1" rollback)"                                 \
         CANCEL   "$(txt "$1" cancel)"
+}
+
+ask_how_to_proceed() {
+    if [[ -n "$YAD" ]] ; then
+        ask_how_to_proceed_yad "$1" ; local ret=$?
+        case "$ret" in
+            1) run_commit   "$1" ;;
+            2) run_rollback "$1" ;;
+            *) echo "Cancel"     ;;
+        esac
+    else
+        case $(ask_how_to_proceed_zenity "$1") in
+            COMMIT)   run_commit   "$1" ;;
+            ROLLBACK) run_rollback "$1" ;;
+            *)        echo "Cancel"     ;;
+        esac
+    fi
 }
 
 run_commit()   { exec "$1" --commit   ; }
@@ -80,12 +120,8 @@ exec_one_job() {
     local JOBDIR="$(dirname "$1")"
     cd "$JOBDIR"
 
-    setup_job
-    case $(ask_how_to_proceed) in
-        COMMIT)   run_commit   "$1" ;;
-        ROLLBACK) run_rollback "$1" ;;
-        *)        echo "Cancel"     ;;
-    esac
+    setup_job "$1"
+    ask_how_to_proceed "$1"
 }
 
 #############3
@@ -97,34 +133,130 @@ jobfield() {
 }
 
 
+rmsg() {
+    local MSG="$1"
+    local -i COL
+    let COL=$(tput cols)-${#MSG}
+    printf "%${COL}s" "$MSG"
+}
+
+job_has_prereqs() {
+    for i in $(jobfield JOB_REQ_FILES_) ; do
+        #echo -en "REQ_file/${jfile##*/} ${i} " 1>&2
+        echo -en "PREREQ/${jfile##*/} ${i} " 1>&2
+        if [[ -e "$i" ]] ; then
+            rmsg "OK!"
+        else
+            echo "MISSING!" 1>&2
+            echo "ERROR: job ${jfile} is requires the file: ${i}" 1>&2
+            return 1
+        fi
+    done
+    return 0
+}
+
 declare -a MENU=()
-select_job() {
-    zenity --list --checklist     \
-        --width=666 --height=420  \
-        --text "Select a job run" \
-        --column "Run?"           \
-        --column "Job Name"       \
-        --column "Original Cmd"   \
+
+select_job_yad() {
+    ${YAD} --list                                                       \
+        --multiple                                                      \
+        --checklist                                                     \
+        --separator=''                                                  \
+        --width 750 --height 280                                        \
+        --center                                                        \
+        --window-icon=media-video                                       \
+        --print-column=2                                                \
+        --hide-column=2                                                 \
+        --column="Run?":CHK                                             \
+        --column="hidden":TEXT                                          \
+        --column="Category":TEXT                                        \
+        --column="Job Name":TEXT                                        \
+        --column="Description":TEXT                                     \
         "${MENU[@]}"
 }
 
-show_and_select_jobs() {
-    local jlist=$(find $JOBLIST -type f -name '*.job')
+select_job_zenity() {
+    ${ZENITY} --list --multiple                                         \
+        --width=800 --height=420                                        \
+        --print-column=1                                                \
+        --hide-column=1                                                 \
+        --text "Select a job run"                                       \
+        --column "Run?"                                                 \
+        --column "Job Name"                                             \
+        --column "Original Cmd"                                         \
+        "${MENU[@]}"
+}
 
-    MENU=()
+job_categories() {
+    ls --directory "${JOBLIST}"/[^._]*
+}
+
+setup_jobselect_menu() {
+    local cat="$(job_categories)"
+    echo find $cat -type f -name '*.job'
+    local jlist=$(find $cat -type f -o -name '*.job')
+
     c=0
     for j in $jlist ; do
         jfile="$j"
-        MENU[$c]="$(basename "$j")"
-        (( c++ ))
-        MENU[$c]="$(jobfield JOB_NAME)"
-        (( c++ ))
-        MENU[$c]="$(jobfield SUMMARY)"
-        (( c++ ))
-        echo -e "MENU=( ${MENU[@]} )\n"
+
+        if job_has_prereqs; then
+            #echo "${jfile##*/}: adding to the menu!" 1>&2
+            if [[ -n "$YAD" ]] ; then
+                #MENU[$c]="TRUE"
+                MENU[$c]="FALSE"
+                (( c++ ))
+            fi
+            MENU[$c]="$(jobfield JOB_BIN)"
+            (( c++ ))
+            MENU[$c]="$(jobfield JOB_DESC_CATEGORY)"
+            (( c++ ))
+            MENU[$c]="$(jobfield JOB_DESC_NAME)"
+            (( c++ ))
+            MENU[$c]="$(jobfield JOB_DESC_SHORT)"
+            (( c++ ))
+            #echo -e "MENU=( ${MENU[@]} )\n"
+        else
+            echo "${jfile##*/}: moving BAD JOBFILE to: ${BADJOBS}" 1>&2
+            mkdir -p "${BADJOBS}"
+            mv "${jfile}" "${BADJOBS}"
+        fi
     done
-    job="$(select_job)"
-echo "job -> $job"
+}
+
+select_with_zenity() {
+    local job jobs="$(select_job_zenity)|"
+    #echo "$jobs"
+    while [[ -n "${jobs}" ]] ; do
+        job="${jobs%%|*}"
+        jobs="${jobs#*|}"
+        exec_one_job "$job"
+    done
+}
+
+select_with_yad() {
+    local job jobs="$(select_job_yad)"
+    IFS=$'\n'
+    for job in ${jobs} ; do
+        if [[ -n "$job" ]] ; then
+            echo "JOB -> [$job]"
+            exec_one_job "$job"
+        fi
+    done
+}
+
+show_and_select_jobs() {
+    MENU=()
+    setup_jobselect_menu "$@"
+    if [[ -n "$YAD" ]] ; then
+        select_with_yad
+    elif [[ -n "$ZENITY" ]] ; then
+        echo "USING ZENITY!"
+        select_with_zenity
+    else
+        echo "Mising: yad or zenity"
+        exit -1
+    fi
 }
 
 ##########
